on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push the SN Docker image
        run: cd .docker && docker build -t b0bl0blawslawbl0g/session-sn-aws:${{github.run_number}} . && docker push b0bl0blawslawbl0g/session-sn-aws:${{github.run_number}}
      - name: Build and push the SS Docker image
        run: cd .docker/storage-server && docker build -t b0bl0blawslawbl0g/session-ss-aws:${{github.run_number}} . && docker push b0bl0blawslawbl0g/session-ss-aws:${{github.run_number}}
      - name: Build and push the Lokinet-Router Docker image
        run: cd .docker/lokinet-router && docker build -t b0bl0blawslawbl0g/session-lokinet-aws:${{github.run_number}} . && docker push b0bl0blawslawbl0g/session-lokinet-aws:${{github.run_number}}
